AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/LineLength:
  Max: 120
